### ISSUE TITLE
ex_doc dependency in all environments

### ISSUE THREAD

**Issue by manuelmontenegro** [elixir-unicode/unicode#3]
In `mix.exs`, the `ex_doc` dependency is listed without the `only: :dev` option, so it is also available in production and testing environments:

https://github.com/elixir-unicode/unicode/blob/e20e43d909f5e3b5fcffc46dcd162001dae51f58/mix.exs#L62

Is there any reason for this? The [ex_doc documentation](https://hexdocs.pm/ex_doc/readme.html#using-exdoc-with-mix) suggests listing this dependency only in `dev` environment. Importing it in all environments implies that all projects that depend on both `unicode` and `ex_doc` are also forced to omit `only: :dev` in their `ex_doc` dependency, in order to avoid conflicts.

**Comment by kipcole9** [comment]
Definitely a bug, thanks for the report. Fixed and published as [ex_unicode version 1.11.1](https://hex.pm/packages/ex_unicode/1.11.1).  Changelog entry is:

### Bug fixes

* Restrict `ex_doc` to only `:dev` and `:release`. Closes #3. Thanks to @manuelmontenegro.
